### ISSUE TITLE
find dae*.apk 是否需要更改为 find dae*.ipk

### ISSUE THREAD

**Issue by JasonNZ668** [douglarek/dae-openwrt#2]
FN=$(find bin/packages -name 'dae*.apk' | sort | head -1 | xargs basename)
          to
          FN=$(find bin/packages -name 'dae*.ipk' | sort | head -1 | xargs basename)

**Comment by douglarek** [comment]
不需要啊，上游改成了 apk 格式，没有 opkg 了。以后不构建 ipk 了。
